name: 'qa-team-aprove'
author: 'wanderbon'
description: 'Github Action to manage QA approves'

inputs:
  githubToken:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  requiredUsers:
    description: List of required users
    required: false
    default: ''

outputs:
  users:
    description: 'Users from requiredUsers who approved pr'

runs:
  using: 'node16'
  main: 'dist/index.js'
